### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by crazyshrut** [PhonePe/drove-cli#7] opened 2024-08-20 10:07 UTC
## Description:
There is a minor typo in the documentation. The word "achieved" is misspelled as "acieved" in the "Connecting to the Drove cluster" section under "Drove CLI config file"

**File:** README.md

**Section:** Connecting to the Drove cluster > Drove CLI config file > Config File format

**Current Text:**

"... supported and can be acieved by using..."

**Suggested Correction:**

"... supported and can be achieved by using..."

And also, CLI is in lower case at most places.

This correction will help improve the readability of the documentation.

**Comment by adityakiran1423** [comment] 2024-11-25 05:33
@santanusinha PR is merged, but the issue is still open?

**Closed** 2024-11-25 06:18 UTC
